// kapeko-track-a-complete/frontend/src/pages/Lab4.tsx
import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import LabNav from '../components/LabNav'
import { getCatalog, enrichProduct } from '../api/client'
import { Product } from '../types/Product'

export default function Lab4() {
  const [products, setProducts] = useState<Product[]>([])
  const [enriched, setEnriched] = useState<Record<string, Product>>({})
  const [enriching, setEnriching] = useState<string | null>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    getCatalog()
      .then(r => setProducts(r.products || []))
      .finally(() => setLoading(false))
  }, [])

  async function enrich(product: Product) {
    setEnriching(product.id)
    try {
      const result = await enrichProduct(product.id)
      setEnriched(e => ({ ...e, [product.id]: result }))
    } finally {
      setEnriching(null)
    }
  }

  const selected = enriched[Object.keys(enriched)[Object.keys(enriched).length - 1]]
  const allDone = products.length > 0 && Object.keys(enriched).length === products.length

  return (
    <div className="min-h-screen bg-stone-950 text-stone-100">
      <LabNav />

      <div className="max-w-3xl mx-auto px-6 py-10">
        <div className="mb-8">
          <p className="text-xs font-semibold text-amber-500 tracking-widest uppercase mb-2">Lab 4</p>
          <h1 className="text-2xl font-light text-white mb-2">Product Content Studio</h1>
          <p className="text-stone-400 text-sm leading-relaxed">
            <code className="text-amber-400">ContentService</code> reads each product from catalog.json,
            sends it to the LLM with Kape Ko brand voice instructions,
            enriches with SEO title, description, marketing hook, and feature bullets.
          </p>
        </div>

        {loading && (
          <p className="text-stone-500 text-sm">Loading catalog from Spring Boot...</p>
        )}

        {!loading && (
          <div className="grid grid-cols-2 gap-3 mb-8">
            {products.map(p => {
              const isEnriched = !!enriched[p.id]
              const isLoading = enriching === p.id
              return (
                <button key={p.id} onClick={() => !isLoading && enrich(p)}
                  className={`p-4 rounded-xl border text-left transition-all ${
                    isEnriched
                      ? 'border-green-600/40 bg-green-950/30'
                      : isLoading
                      ? 'border-amber-500/40 bg-amber-950/20'
                      : 'border-stone-800 bg-stone-900 hover:border-stone-700'
                  }`}>
                  <div className="flex justify-between items-start mb-1">
                    <span className="text-xs text-stone-500">{p.id}</span>
                    {isEnriched && <span className="text-green-400 text-xs">✓ enriched</span>}
                    {isLoading && <span className="text-amber-400 text-xs animate-pulse">generating...</span>}
                  </div>
                  <p className="text-sm font-medium text-white">{p.name}</p>
                  <p className="text-xs text-stone-500 mt-0.5">{p.roast} · {p.origin.split(',')[0]}</p>
                </button>
              )
            })}
          </div>
        )}

        {/* Content preview */}
        {selected && (
          <div className="bg-stone-900 border border-stone-800 rounded-xl p-6 mb-6">
            <p className="text-xs text-stone-500 mb-4 font-mono">
              POST /api/products/{selected.id}/enrich → 200 OK
            </p>
            <div className="space-y-4">
              <div>
                <p className="text-xs text-stone-500 mb-1">SEO Title</p>
                <p className="text-sm font-medium text-white">{selected.seo_title}</p>
              </div>
              <div>
                <p className="text-xs text-stone-500 mb-1">Marketing Hook</p>
                <p className="text-base italic text-amber-400">"{selected.marketing_hook}"</p>
              </div>
              <div>
                <p className="text-xs text-stone-500 mb-1">Product Description</p>
                <p className="text-sm text-stone-300 leading-relaxed line-clamp-4">
                  {selected.product_description}
                </p>
              </div>
              {selected.feature_bullets && (
                <div>
                  <p className="text-xs text-stone-500 mb-2">Feature Bullets</p>
                  <ul className="space-y-1">
                    {selected.feature_bullets.map((b, i) => (
                      <li key={i} className="text-xs text-stone-400 flex gap-2">
                        <span className="text-amber-500">▸</span>{b}
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </div>
          </div>
        )}

        {allDone && (
          <Link to="/"
            className="block w-full text-center bg-amber-500 hover:bg-amber-600 text-white
              font-semibold py-3.5 rounded-xl transition-colors">
            Lab 5: View the Storefront →
          </Link>
        )}
        {!allDone && products.length > 0 && (
          <p className="text-center text-stone-500 text-sm">
            Click each product to enrich it ({Object.keys(enriched).length}/{products.length} done)
          </p>
        )}
      </div>
    </div>
  )
}

// kapeko-track-b-complete/frontend/src/app/pages/lab4/lab4.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { LabNavComponent } from '../../components/lab-nav/lab-nav.component';
import { ProductService } from '../../services/product.service';
import { Product } from '../../models/product.model';

@Component({
  selector: 'app-lab4',
  standalone: true,
  imports: [LabNavComponent, CommonModule, RouterModule],
  template: `
    <app-lab-nav />
    <div style="max-width:720px;margin:0 auto;padding:32px 24px">
      <p style="color:#F59E0B;font-size:11px;font-weight:600;letter-spacing:2px;text-transform:uppercase;margin-bottom:8px">Lab 4</p>
      <h1 style="color:#1C1917;font-size:24px;font-weight:300;margin-bottom:8px">Product Content Studio</h1>
      <p style="color:#78716C;font-size:13px;margin-bottom:24px">Click each product to enrich with AI-generated SEO title, description, and marketing hook</p>

      <p *ngIf="loading" style="color:#78716C;font-size:13px">Loading catalog from Spring Boot...</p>

      <div *ngIf="!loading" style="display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-bottom:20px">
        <button *ngFor="let p of products" (click)="enrich(p)"
          [style.background]="enriched[p.id] ? '#052E16' : enriching === p.id ? '#1C1004' : '#0F172A'"
          [style.border-color]="enriched[p.id] ? '#16A34A' : enriching === p.id ? '#F59E0B' : '#1E293B'"
          style="border:0.5px solid;border-radius:10px;padding:14px;text-align:left;cursor:pointer;transition:all .15s">
          <div style="display:flex;justify-content:space-between;margin-bottom:6px">
            <span style="font-size:10px;color:#475569">{{p.id}}</span>
            <span *ngIf="enriched[p.id]" style="font-size:10px;color:#34D399">✓ enriched</span>
            <span *ngIf="enriching === p.id" style="font-size:10px;color:#F59E0B">generating...</span>
          </div>
          <div style="font-size:13px;font-weight:500;color:#fff;margin-bottom:4px">{{p.name}}</div>
          <div style="font-size:11px;color:#475569">{{p.roast}}</div>
        </button>
      </div>

      <div *ngIf="selected"
        style="background:#fff;border:0.5px solid #E7E5E4;border-radius:10px;padding:16px;margin-bottom:20px">
        <div style="margin-bottom:12px">
          <div style="font-size:10px;color:#A8A29E;text-transform:uppercase;letter-spacing:.5px;margin-bottom:4px">SEO Title</div>
          <div style="font-size:13px;color:#1C1917">{{selected.seo_title}}</div>
        </div>
        <div style="margin-bottom:12px">
          <div style="font-size:10px;color:#A8A29E;text-transform:uppercase;letter-spacing:.5px;margin-bottom:4px">Marketing Hook</div>
          <em style="font-size:16px;color:#D97706">"{{selected.marketing_hook}}"</em>
        </div>
        <div>
          <div style="font-size:10px;color:#A8A29E;text-transform:uppercase;letter-spacing:.5px;margin-bottom:4px">Description</div>
          <div style="font-size:12px;color:#57534E;line-height:1.6">{{selected.product_description}}</div>
        </div>
      </div>

      <a *ngIf="allDone" routerLink="/"
        style="display:block;text-align:center;background:#F59E0B;color:#fff;padding:12px;border-radius:10px;text-decoration:none;font-weight:600;font-size:14px">
        Lab 5: View Storefront →
      </a>
      <p *ngIf="!allDone && products.length > 0" style="text-align:center;color:#78716C;font-size:13px">
        Click each product to enrich ({{enrichedCount}}/{{products.length}} done)
      </p>
    </div>
  `
})
export class Lab4Component implements OnInit {
  products: Product[] = [];
  enriched: Record<string, Product> = {};
  enriching: string | null = null;
  selected: Product | null = null;
  loading = true;

  constructor(private productService: ProductService) {}

  ngOnInit() {
    this.productService.getCatalog().subscribe({
      next: (r) => { this.products = r.products || []; this.loading = false; },
      error: () => { this.loading = false; },
    });
  }

  get allDone() { return this.products.length > 0 && this.enrichedCount === this.products.length; }
  get enrichedCount() { return Object.keys(this.enriched).length; }

  enrich(p: Product) {
    if (this.enriching) return;
    this.enriching = p.id;
    this.productService.enrichProduct(p.id).subscribe({
      next: (r) => { this.enriched[p.id] = r; this.selected = r; this.enriching = null; },
      error: () => { this.enriching = null; },
    });
  }
}
